### ISSUE TITLE
ConcurrentModificationException in SoyCacheUpdater when reloading project

### ISSUE THREAD

**Issue by evenaglia** [Non-Dairy-Soy-Plugin/Non-Dairy-Soy-Plugin#12]
Error while indexing /Users/ed.venaglia/Jive/src/appsmarket/sbs/themes_5_0_2/jivedevelopers/soy/nav/navbar.soy
To reindex this file IDEA has to be restarted
java.util.ConcurrentModificationException
    at java.util.HashMap$HashIterator.remove(HashMap.java:811)
    at net.venaglia.nondairy.soylang.cache.AbstractTemplateCache.removeImpl(AbstractTemplateCache.java:93)
    at net.venaglia.nondairy.soylang.cache.AbstractTemplateCache.removeFile(AbstractTemplateCache.java:81)
    at net.venaglia.nondairy.soylang.cache.AbstractTemplateCache.addFile(AbstractTemplateCache.java:67)
    at net.venaglia.nondairy.soylang.cache.SoyCacheUpdater.updateCacheImpl(SoyCacheUpdater.java:188)
    at net.venaglia.nondairy.soylang.cache.SoyCacheUpdater.updateCache(SoyCacheUpdater.java:140)
    at net.venaglia.nondairy.soylang.cache.SoyCacheUpdater.processFile(SoyCacheUpdater.java:111)
    at com.intellij.openapi.project.CacheUpdateSession.processFile(CacheUpdateSession.java:102)
    at com.intellij.openapi.project.CacheUpdateRunner$MyRunnable$1.run(CacheUpdateRunner.java:231)
    at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:940)
    at com.intellij.openapi.project.CacheUpdateRunner$MyRunnable.run(CacheUpdateRunner.java:237)
    at com.intellij.openapi.application.impl.ApplicationImpl$8.run(ApplicationImpl.java:454)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:439)
    at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303)
    at java.util.concurrent.FutureTask.run(FutureTask.java:138)
    at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:895)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:918)
    at java.lang.Thread.run(Thread.java:695)
    at com.intellij.openapi.application.impl.ApplicationImpl$1$1.run(ApplicationImpl.java:152)

**Comment by omayevskiy** [comment]
+1
```
Error while indexing *************my.soy
To reindex this file IDEA has to be restarted
java.util.ConcurrentModificationException
	at java.util.HashMap$HashIterator.nextEntry(HashMap.java:793)
	at java.util.HashMap$KeyIterator.next(HashMap.java:828)
	at net.venaglia.nondairy.soylang.cache.AbstractTemplateCache.removeImpl(AbstractTemplateCache.java:91)
	at net.venaglia.nondairy.soylang.cache.AbstractTemplateCache.removeFile(AbstractTemplateCache.java:81)
	at net.venaglia.nondairy.soylang.cache.AbstractTemplateCache.addFile(AbstractTemplateCache.java:67)
	at net.venaglia.nondairy.soylang.cache.SoyCacheUpdater.updateCacheImpl(SoyCacheUpdater.java:188)
	at net.venaglia.nondairy.soylang.cache.SoyCacheUpdater.updateCache(SoyCacheUpdater.java:140)
	at net.venaglia.nondairy.soylang.cache.SoyCacheUpdater.processFile(SoyCacheUpdater.java:111)
	at com.intellij.openapi.project.CacheUpdateSession.processFile(CacheUpdateSession.java:108)
	at com.intellij.openapi.project.CacheUpdateRunner$1.consume(CacheUpdateRunner.java:84)
	at com.intellij.openapi.project.CacheUpdateRunner$1.consume(CacheUpdateRunner.java:81)
	at com.intellij.openapi.project.CacheUpdateRunner$MyRunnable$1.run(CacheUpdateRunner.java:290)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1098)
	at com.intellij.openapi.project.CacheUpdateRunner$MyRunnable$2.run(CacheUpdateRunner.java:310)
	at com.intellij.openapi.progress.impl.CoreProgressManager$2.run(CoreProgressManager.java:152)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:452)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:449)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:402)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:137)
	at com.intellij.openapi.project.CacheUpdateRunner$MyRunnable.run(CacheUpdateRunner.java:304)
	at com.intellij.openapi.application.impl.ApplicationImpl$8.run(ApplicationImpl.java:400)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:439)
	at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303)
	at java.util.concurrent.FutureTask.run(FutureTask.java:138)
	at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:895)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:918)
	at java.lang.Thread.run(Thread.java:695)
	at org.jetbrains.ide.PooledThreadExecutor$1$1.run(PooledThreadExecutor.java:56)



java.util.ConcurrentModificationException
	at java.util.HashMap$HashIterator.nextEntry(HashMap.java:793)
	at java.util.HashMap$KeyIterator.next(HashMap.java:828)
	at net.venaglia.nondairy.soylang.cache.AbstractTemplateCache.removeImpl(AbstractTemplateCache.java:91)
	at net.venaglia.nondairy.soylang.cache.AbstractTemplateCache.removeFile(AbstractTemplateCache.java:81)
	at net.venaglia.nondairy.soylang.cache.AbstractTemplateCache.addFile(AbstractTemplateCache.java:67)
	at net.venaglia.nondairy.soylang.cache.SoyCacheUpdater.updateCacheImpl(SoyCacheUpdater.java:188)
	at net.venaglia.nondairy.soylang.cache.SoyCacheUpdater.updateCache(SoyCacheUpdater.java:140)
	at net.venaglia.nondairy.soylang.cache.SoyCacheUpdater.processFile(SoyCacheUpdater.java:111)
	at com.intellij.openapi.project.CacheUpdateSession.processFile(CacheUpdateSession.java:108)
	at com.intellij.openapi.project.CacheUpdateRunner$1.consume(CacheUpdateRunner.java:84)
	at com.intellij.openapi.project.CacheUpdateRunner$1.consume(CacheUpdateRunner.java:81)
	at com.intellij.openapi.project.CacheUpdateRunner$MyRunnable$1.run(CacheUpdateRunner.java:290)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1098)
	at com.intellij.openapi.project.CacheUpdateRunner$MyRunnable$2.run(CacheUpdateRunner.java:310)
	at com.intellij.openapi.progress.impl.CoreProgressManager$2.run(CoreProgressManager.java:152)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:452)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:449)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:402)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:137)
	at com.intellij.openapi.project.CacheUpdateRunner$MyRunnable.run(CacheUpdateRunner.java:304)
	at com.intellij.openapi.application.impl.ApplicationImpl$8.run(ApplicationImpl.java:400)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:439)
	at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303)
	at java.util.concurrent.FutureTask.run(FutureTask.java:138)
	at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:895)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:918)
	at java.lang.Thread.run(Thread.java:695)
	at org.jetbrains.ide.PooledThreadExecutor$1$1.run(PooledThreadExecutor.java:56)



java.util.ConcurrentModificationException
	at java.util.HashMap$HashIterator.nextEntry(HashMap.java:793)
	at java.util.HashMap$KeyIterator.next(HashMap.java:828)
	at net.venaglia.nondairy.soylang.cache.AbstractTemplateCache.removeImpl(AbstractTemplateCache.java:91)
	at net.venaglia.nondairy.soylang.cache.AbstractTemplateCache.removeFile(AbstractTemplateCache.java:81)
	at net.venaglia.nondairy.soylang.cache.AbstractTemplateCache.addFile(AbstractTemplateCache.java:67)
	at net.venaglia.nondairy.soylang.cache.SoyCacheUpdater.updateCacheImpl(SoyCacheUpdater.java:188)
	at net.venaglia.nondairy.soylang.cache.SoyCacheUpdater.updateCache(SoyCacheUpdater.java:140)
	at net.venaglia.nondairy.soylang.cache.SoyCacheUpdater.processFile(SoyCacheUpdater.java:111)
	at com.intellij.openapi.project.CacheUpdateSession.processFile(CacheUpdateSession.java:108)
	at com.intellij.openapi.project.CacheUpdateRunner$1.consume(CacheUpdateRunner.java:84)
	at com.intellij.openapi.project.CacheUpdateRunner$1.consume(CacheUpdateRunner.java:81)
	at com.intellij.openapi.project.CacheUpdateRunner$MyRunnable$1.run(CacheUpdateRunner.java:290)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1098)
	at com.intellij.openapi.project.CacheUpdateRunner$MyRunnable$2.run(CacheUpdateRunner.java:310)
	at com.intellij.openapi.progress.impl.CoreProgressManager$2.run(CoreProgressManager.java:152)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:452)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:449)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:402)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:137)
	at com.intellij.openapi.project.CacheUpdateRunner$MyRunnable.run(CacheUpdateRunner.java:304)
	at com.intellij.openapi.application.impl.ApplicationImpl$8.run(ApplicationImpl.java:400)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:439)
	at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303)
	at java.util.concurrent.FutureTask.run(FutureTask.java:138)
	at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:895)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:918)
	at java.lang.Thread.run(Thread.java:695)
	at org.jetbrains.ide.PooledThreadExecutor$1$1.run(PooledThreadExecutor.java:56)




```
