### ISSUE TITLE
Fatal Error

### ISSUE THREAD

**Issue by kornilova203** [Non-Dairy-Soy-Plugin/Non-Dairy-Soy-Plugin#36]
```
null
java.lang.UnsupportedOperationException
	at net.venaglia.nondairy.soylang.elements.path.PsiElementCollection$1.remove(PsiElementCollection.java:57)
	at net.venaglia.nondairy.soylang.inspection.ParameterAlreadyDeclaredInspection.findProblems(ParameterAlreadyDeclaredInspection.java:77)
	at net.venaglia.nondairy.soylang.inspection.AbstractSoyInspection.checkFile(AbstractSoyInspection.java:104)
	at com.intellij.codeInspection.LocalInspectionTool$1.visitFile(LocalInspectionTool.java:142)
	at com.intellij.extapi.psi.PsiFileBase.accept(PsiFileBase.java:70)
	at com.intellij.codeInspection.InspectionEngine.acceptElements(InspectionEngine.java:82)
	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.a(LocalInspectionsPass.java:309)
	at com.intellij.concurrency.ApplierCompleter.d(ApplierCompleter.java:133)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1127)
	at com.intellij.concurrency.ApplierCompleter.b(ApplierCompleter.java:105)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:543)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:488)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:94)
	at com.intellij.concurrency.ApplierCompleter.a(ApplierCompleter.java:116)
	at com.intellij.concurrency.ApplierCompleter.b(ApplierCompleter.java:96)
	at com.intellij.openapi.application.impl.ReadMostlyRWLock.executeByImpatientReader(ReadMostlyRWLock.java:143)
	at com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:229)
	at com.intellij.concurrency.ApplierCompleter.compute(ApplierCompleter.java:96)
	at java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:731)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
```

**Comment by SerCeMan** [comment]
Hi, @kornilova-l!

The development of the non-dairy soy plugin has stopped. There is a new closure templates (soy) plugin now: https://github.com/google/bamboo-soy officially supported by Google. I advise you to try bamboo instead, it is already covering most of the non-dairy plugin functionality.
